### ISSUE TITLE
Odometry is a bit off

### ISSUE THREAD

**Issue by oleorhagen** [srmainwaring/steer_bot#10]
I don't know if you care about this or not, or if this is even still on your radar. But having tried the package, and started the car just doing a loop, odometry drifts a fair bit, just driving the car in a circle.

**Comment by srmainwaring** [comment]
I have not checked the steering angle, wheel velocity and odometry calculations in steer_drive_ros and ackermann_steering_controller: for this project I have assumed them to be correct. The controllers require the steering geometry, the model has a wheel separation of 0.4m (lateral and longitudinal) set in the urdf and this is mirrored in the controller config. The dimensions were deliberately simplified to try and reduce this as a source of error.

This leaves the friction physics in Gazebo and the settings allow for wheel slippage. There is some slippage in the direction of the wheel rotation, and also slippage in the perpendicular which is most noticeable of you turn sharply at high speed (the rover will drift). I think this is the cause of the odometer drift, but can look into the controller calculations and config if you think there is an error there.

**Comment by oleorhagen** [comment]
I guess it might be the drift then. I haven't looked into it though. Thanks for your reply. I had a quick look at the code for the controller, and on the surface it looks correct to me.
