### ISSUE TITLE
NavigationStack integration

### ISSUE THREAD

**Issue by dinimar** [srmainwaring/steer_bot#12]
NavigationStack allows to add robot autonomous navigation. There are [tutorials](http://wiki.ros.org/navigation/Tutorials) on ROS wiki. But they're not some step-by-step tutorial they explain NavigationStack in general. So, it'll be nice for your repository and for all ROS community to have NavigationStack and step-by-step instruction with all your experienced you faced when integrated Navigation.

Things to add:
- Sensor with topics of sensor_msgs
- SLAM (gmapping, hector)
- Planner ([teb_local_planner](http://wiki.ros.org/teb_local_planner/Tutorials) developed exactly for ackermann vehicles)

P.S. I added this issue because I need integrate NavigationStack with teb_local_planner for my robot (also ackermann vehicle). Your robot is the best example of non-holonomic vehicle with ROS and Gazebo implementation. So, I can learn teb_local_planner on your robot and then integrate it to my robot. But, at the moment, you don't have Kinetic version #11, therefore I can't launch it. I've tried to build it, it've been built. But it does'nt launch. I can help you with both of those issues, if you want.

**Comment by srmainwaring** [comment]
@dinimar I appreciate the feedback and suggestion but would like to leave this repo focussed on the quite specific example of setting up the ackermann-steering_controller for a simple vehicle.

I originally put this together in response to a question in one of my other projects, and the concept was to have a minimal example that only contained the urdf and control configuration to demonstrate the use of ros_control. If I add sensors, navigation, SLAM etc. then someone just looking to set up the controller would need to ignore the additional code (and know what to ignore).

**Comment by dinimar** [comment]
@srmainwaring Sure, but what about Kinetic version #11. If repo will have Kinetic version, I can easily fork rep and extend it till the NavigationStack

**Comment by srmainwaring** [comment]
Yes - I'll take a look into what's involved to back-porting to kinetic.
