### ISSUE TITLE
Apply to a new robot

### ISSUE THREAD

**Issue by tomlogan501** [srmainwaring/steer_bot#17]
Hi,
I try to apply this project to my robot and it seems to fail register the correct joint

> 
> started roslaunch server http://ubuntu:38463/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /f190/ackermann_steering_controller/front_steer: front_steer_joint
>  * /f190/ackermann_steering_controller/open_loop: False
>  * /f190/ackermann_steering_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
>  * /f190/ackermann_steering_controller/publish_rate: 50
>  * /f190/ackermann_steering_controller/rear_wheel: rear_wheel_joint
>  * /f190/ackermann_steering_controller/twist_covariance_diagonal: [0.001, 0.001, 10...
>  * /f190/ackermann_steering_controller/type: ackermann_steerin...
>  * /f190/gains/rear_left_wheel_joint/d: 10.0
>  * /f190/gains/rear_left_wheel_joint/i: 0.5
>  * /f190/gains/rear_left_wheel_joint/i_clamp: 3.0
>  * /f190/gains/rear_left_wheel_joint/p: 100000.0
>  * /f190/gains/rear_right_wheel_joint/d: 10.0
>  * /f190/gains/rear_right_wheel_joint/i: 0.5
>  * /f190/gains/rear_right_wheel_joint/i_clamp: 3.0
>  * /f190/gains/rear_right_wheel_joint/p: 100000.0
>  * /f190/gazebo/enable_ros_network: True
>  * /f190/joint_state_publisher/publish_rate: 50
>  * /f190/joint_state_publisher/type: joint_state_contr...
>  * /f190/robot_description: <?xml version="1....
>  * /f190/robot_state_publisher/publish_frequency: 50.0
>  * /f190/rqt_robot_steering/default_topic: /f190/ackermann_s...
>  * /f190/steer_bot_hardware_gazebo/enable_ackermann_link: True
>  * /f190/steer_bot_hardware_gazebo/front_steer: front_steer_joint
>  * /f190/steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
>  * /f190/steer_bot_hardware_gazebo/virtual_front_steers: ['front_right_ste...
>  * /f190/steer_bot_hardware_gazebo/virtual_front_wheels: ['front_right_whe...
>  * /f190/steer_bot_hardware_gazebo/virtual_rear_wheels: ['rear_right_whee...
>  * /f190/steer_bot_hardware_gazebo/wheel_separation_h: 1.945
>  * /f190/steer_bot_hardware_gazebo/wheel_separation_w: 1.1
>  * /rosdistro: melodic
>  * /rosversion: 1.14.11
>  * /use_sim_time: True
> 
> NODES
>   /f190/
>     controller_spawner (controller_manager/spawner)
>     gazebo (gazebo_ros/gzserver)
>     gazebo_gui (gazebo_ros/gzclient)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
>     spawn_vehicle (gazebo_ros/spawn_model)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[f190/gazebo-1]: started with pid [4563]
> process[f190/gazebo_gui-2]: started with pid [4568]
> process[f190/controller_spawner-3]: started with pid [4572]
> process[f190/robot_state_publisher-4]: started with pid [4574]
> process[f190/rqt_robot_steering-5]: started with pid [4575]
> process[f190/spawn_vehicle-6]: started with pid [4577]
> [INFO] [1623836194.832917, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [ INFO] [1623836195.081181641]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1623836195.091992604]: waitForService: Service [/f190/gazebo/set_physics_properties] has not been advertised, waiting...
> [ INFO] [1623836195.188137257]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1623836195.190479774]: waitForService: Service [/f190/gazebo_gui/set_physics_properties] has not been advertised, waiting...
> [INFO] [1623836195.459936, 0.000000]: Loading model XML from ros parameter robot_description
> [INFO] [1623836195.473344, 0.000000]: Waiting for service //f190/gazebo/spawn_urdf_model
> [ INFO] [1623836196.673612618, 0.004000000]: waitForService: Service [/f190/gazebo/set_physics_properties] is now available.
> [INFO] [1623836196.694260, 0.000000]: Calling service //f190/gazebo/spawn_urdf_model
> [ INFO] [1623836196.704523313, 0.030000000]: Physics dynamic reconfigure ready.
> [INFO] [1623836196.872174, 0.133000]: Spawn status: SpawnModel: Successfully spawned entity
> [ INFO] [1623836196.925240247, 0.133000000]: Loading gazebo_ros_control plugin
> [ INFO] [1623836196.925480080, 0.133000000]: Starting gazebo_ros_control plugin in namespace: f190
> [ INFO] [1623836196.926812355, 0.133000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/f190/robot_description] on the ROS param server.
> [ INFO] [1623836197.054893570, 0.133000000]: Registered joint ' ' in the JointStateInterface
> [ INFO] [1623836197.056141495, 0.133000000]: Registered joint ' ' in the CommandJointInterface
> [ WARN] [1623836197.056556726, 0.133000000]: Replacing previously registered handle '' in 'hardware_interface::JointStateInterface'.
> [ INFO] [1623836197.056727345, 0.133000000]: Registered joint ' ' in the JointStateInterface
> [ INFO] [1623836197.056918185, 0.133000000]: Registered joint ' ' in the CommandJointInterface
> [ INFO] [1623836197.062063686, 0.133000000]: wheel_separation_w = 6.92262e-310
> [ INFO] [1623836197.062344813, 0.133000000]: wheel_separation_h = 3.60739e-313
> [ INFO] [1623836197.063136080, 0.133000000]: enable_ackermann_link = true

Here is my current launch file 

> 
> <?xml version="1.0"?>
> <launch>
> 
>     <arg name="model" default="$(find f190_description)/urdf/f190.urdf.xacro"/>
>     <arg name="namespace" default="/f190" />
>     <arg name="world_name" default="worlds/empty_world" />
>     <arg name="cmd_timeout" default="0.5"/>
>     <arg name="x" default="0.0"/>
>     <arg name="y" default="0.0"/>
>     <arg name="z" default="1.0" />
>     <arg name="roll" default="0.0"/>
>     <arg name="pitch" default="0.0"/>
>     <arg name="yaw" default="0.0"/>
> 
>     <group ns="$(arg namespace)">
> 
>         
>         <include file="$(find gazebo_ros)/launch/empty_world.launch">
>             <arg name="world_name" default="$(arg world_name)"/>
>         </include>
> 
>         
>         <param name="robot_description" command="$(find xacro)/xacro $(arg model)"/>
> 
>         
>         <rosparam file="$(find f190_control)/config/ctrl_ackermann_steering_controller.yaml" command="load" ns="$(arg namespace)" />
>         <rosparam file="$(find f190_control)/config/ctrl_gains.yaml" command="load" ns="$(arg namespace)" />
>         <rosparam file="$(find f190_control)/config/ctrl_joint_state_publisher.yaml" command="load" ns="$(arg namespace)" />
>         <rosparam file="$(find f190_control)/config/ctrl_steer_bot_hardware_gazebo.yaml" command="load" ns="$(arg namespace)" />
> 
>         
>         <node pkg="controller_manager" type="spawner" name="controller_spawner" ns="$(arg namespace)"
>             args="joint_state_publisher ackermann_steering_controller"
>             output="screen" respawn="false" />
> 
>         
>         <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher">
>             <param name="publish_frequency" value="50.0"/>
>         </node>
> 
>         
>         <node pkg="rqt_robot_steering" type="rqt_robot_steering" name="rqt_robot_steering" >
>             <param name="default_topic" value="$(arg namespace)/ackermann_steering_controller/cmd_vel"/>
>         </node>
> 
>         
>         <node name="spawn_vehicle" pkg="gazebo_ros" type="spawn_model"
>             args="-urdf -param robot_description -model f190
>                 -gazebo_namespace /$(arg namespace)/gazebo
>                 -x $(arg x) -y $(arg y) -z $(arg z)
>                 -R $(arg roll) -P $(arg pitch) -Y $(arg yaw)"
>             respawn="false" output="screen" />
> 
>     </group>
> 
> </launch>

**Comment by tomlogan501** [comment]
My bad, it seems that the namespace should be "/f190" in the urdf and not just "f190"

It loads but without any display in gazebo 

> started roslaunch server http://ubuntu:46339/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /f190/ackermann_steering_controller/front_steer: front_steer_joint
>  * /f190/ackermann_steering_controller/open_loop: False
>  * /f190/ackermann_steering_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
>  * /f190/ackermann_steering_controller/publish_rate: 50
>  * /f190/ackermann_steering_controller/rear_wheel: rear_wheel_joint
>  * /f190/ackermann_steering_controller/twist_covariance_diagonal: [0.001, 0.001, 10...
>  * /f190/ackermann_steering_controller/type: ackermann_steerin...
>  * /f190/gains/rear_left_wheel_joint/d: 10.0
>  * /f190/gains/rear_left_wheel_joint/i: 0.5
>  * /f190/gains/rear_left_wheel_joint/i_clamp: 3.0
>  * /f190/gains/rear_left_wheel_joint/p: 100000.0
>  * /f190/gains/rear_right_wheel_joint/d: 10.0
>  * /f190/gains/rear_right_wheel_joint/i: 0.5
>  * /f190/gains/rear_right_wheel_joint/i_clamp: 3.0
>  * /f190/gains/rear_right_wheel_joint/p: 100000.0
>  * /f190/gazebo/enable_ros_network: True
>  * /f190/joint_state_publisher/publish_rate: 50
>  * /f190/joint_state_publisher/type: joint_state_contr...
>  * /f190/robot_description: <?xml version="1....
>  * /f190/robot_state_publisher/publish_frequency: 50.0
>  * /f190/rqt_robot_steering/default_topic: /f190/ackermann_s...
>  * /f190/steer_bot_hardware_gazebo/enable_ackermann_link: True
>  * /f190/steer_bot_hardware_gazebo/front_steer: front_steer_joint
>  * /f190/steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
>  * /f190/steer_bot_hardware_gazebo/virtual_front_steers: ['front_right_ste...
>  * /f190/steer_bot_hardware_gazebo/virtual_front_wheels: ['front_right_whe...
>  * /f190/steer_bot_hardware_gazebo/virtual_rear_wheels: ['rear_right_whee...
>  * /f190/steer_bot_hardware_gazebo/wheel_separation_h: 1.945
>  * /f190/steer_bot_hardware_gazebo/wheel_separation_w: 1.1
>  * /rosdistro: melodic
>  * /rosversion: 1.14.11
>  * /use_sim_time: True
> 
> NODES
>   /f190/
>     controller_spawner (controller_manager/spawner)
>     gazebo (gazebo_ros/gzserver)
>     gazebo_gui (gazebo_ros/gzclient)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
>     spawn_vehicle (gazebo_ros/spawn_model)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[f190/gazebo-1]: started with pid [5164]
> process[f190/gazebo_gui-2]: started with pid [5169]
> process[f190/controller_spawner-3]: started with pid [5174]
> process[f190/robot_state_publisher-4]: started with pid [5175]
> process[f190/rqt_robot_steering-5]: started with pid [5176]
> process[f190/spawn_vehicle-6]: started with pid [5177]
> [INFO] [1623836723.211339, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [ INFO] [1623836723.358516559]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1623836723.361576068]: waitForService: Service [/f190/gazebo/set_physics_properties] has not been advertised, waiting...
> [ INFO] [1623836723.425390857]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1623836723.428192769]: waitForService: Service [/f190/gazebo_gui/set_physics_properties] has not been advertised, waiting...
> [INFO] [1623836723.764732, 0.000000]: Loading model XML from ros parameter robot_description
> [INFO] [1623836723.787158, 0.000000]: Waiting for service //f190/gazebo/spawn_urdf_model
> [ INFO] [1623836724.473816447]: waitForService: Service [/f190/gazebo/set_physics_properties] is now available.
> [ INFO] [1623836724.531812737, 0.014000000]: Physics dynamic reconfigure ready.
> [INFO] [1623836724.697361, 0.158000]: Calling service //f190/gazebo/spawn_urdf_model
> [INFO] [1623836724.868770, 0.301000]: Spawn status: SpawnModel: Successfully spawned entity
> [ INFO] [1623836724.906174154, 0.301000000]: Loading gazebo_ros_control plugin
> [ INFO] [1623836724.906673894, 0.301000000]: Starting gazebo_ros_control plugin in namespace: /f190
> [ INFO] [1623836724.907386800, 0.301000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/f190/robot_description] on the ROS param server.
> [ INFO] [1623836725.045663772, 0.301000000]: Registered joint 'front_steer_joint ' in the JointStateInterface
> [ INFO] [1623836725.047061571, 0.301000000]: Registered joint 'front_steer_joint ' in the CommandJointInterface
> [ INFO] [1623836725.047440674, 0.301000000]: Registered joint 'front_right_steer_joint ' in the JointStateInterface
> [ INFO] [1623836725.047706018, 0.301000000]: Registered joint 'front_right_steer_joint ' in the CommandJointInterface
> [ INFO] [1623836725.047886801, 0.301000000]: Registered joint 'front_left_steer_joint ' in the JointStateInterface
> [ INFO] [1623836725.048061784, 0.301000000]: Registered joint 'front_left_steer_joint ' in the CommandJointInterface
> [ INFO] [1623836725.048303481, 0.301000000]: Registered joint 'rear_wheel_joint ' in the JointStateInterface
> [ INFO] [1623836725.048500986, 0.301000000]: Registered joint 'rear_wheel_joint ' in the CommandJointInterface
> [ INFO] [1623836725.048761722, 0.301000000]: Registered joint 'rear_right_wheel_joint ' in the JointStateInterface
> [ INFO] [1623836725.048958592, 0.301000000]: Registered joint 'rear_right_wheel_joint ' in the CommandJointInterface
> [ INFO] [1623836725.049185464, 0.301000000]: Registered joint 'rear_left_wheel_joint ' in the JointStateInterface
> [ INFO] [1623836725.049377338, 0.301000000]: Registered joint 'rear_left_wheel_joint ' in the CommandJointInterface
> [ INFO] [1623836725.049576734, 0.301000000]: Registered joint 'front_right_wheel_joint ' in the JointStateInterface
> [ INFO] [1623836725.049807868, 0.301000000]: Registered joint 'front_left_wheel_joint ' in the JointStateInterface
> [ INFO] [1623836725.056693623, 0.301000000]: wheel_separation_w = 1.1
> [ INFO] [1623836725.057015151, 0.301000000]: wheel_separation_h = 1.945
> [ INFO] [1623836725.059773407, 0.301000000]: enable_ackermann_link = true
> [ WARN] [1623836725.060899162, 0.301000000]: Joint limits won't be enforced for joint 'front_left_steer_joint'.
> [ WARN] [1623836725.061328125, 0.301000000]: Joint limits won't be enforced for joint 'front_right_steer_joint'.
> [ INFO] [1623836725.061994735, 0.301000000]: Trying to set pid param of 'rear_right_wheel_joint ' at PID proc in init()
> [ INFO] [1623836725.087368781, 0.301000000]: Succeeded to set pid param of 'rear_right_wheel_joint ' at PID proc in init()
> [ INFO] [1623836725.087708196, 0.301000000]: Trying to set pid param of 'rear_left_wheel_joint ' at PID proc in init()
> [ INFO] [1623836725.106195437, 0.301000000]: Succeeded to set pid param of 'rear_left_wheel_joint ' at PID proc in init()
> [ INFO] [1623836725.111813574, 0.301000000]: Loaded gazebo_ros_control.
> [f190/spawn_vehicle-6] process has finished cleanly
> log file: /home/colas/.ros/log/95b1a29e-ce84-11eb-93b4-000c2924b415/f190-spawn_vehicle-6*.log
> [INFO] [1623836725.323982, 0.504000]: Controller Spawner: Waiting for service controller_manager/switch_controller
> [INFO] [1623836725.330078, 0.509000]: Controller Spawner: Waiting for service controller_manager/unload_controller
> [INFO] [1623836725.334918, 0.513000]: Loading controller: joint_state_publisher
> [INFO] [1623836725.356235, 0.530000]: Loading controller: ackermann_steering_controller
> [ INFO] [1623836725.407640902, 0.579000000]: Controller state will be published at 50Hz.
> [ INFO] [1623836725.410968340, 0.583000000]: Wheel separation height will be multiplied by 1.
> [ INFO] [1623836725.412641544, 0.585000000]: Wheel radius will be multiplied by 1.
> [ INFO] [1623836725.413555426, 0.586000000]: Steer pos will be multiplied by 1.
> [ INFO] [1623836725.415960837, 0.588000000]: Velocity rolling window size of 10.
> [ INFO] [1623836725.418573990, 0.591000000]: Velocity commands will be considered old if they are older than 0.5s.
> [ INFO] [1623836725.420341420, 0.593000000]: Allow mutiple cmd_vel publishers is enabled
> [ INFO] [1623836725.433492886, 0.597000000]: Base frame_id set to base_link
> [ INFO] [1623836725.434234009, 0.598000000]: Odometry frame_id set to odom
> [ INFO] [1623836725.435058921, 0.599000000]: Publishing to tf is enabled
> [ INFO] [1623836725.443732203, 0.608000000]: rear wheel to origin: -1.45,0, 0
> [ INFO] [1623836725.443787421, 0.608000000]: front steer to origin: 1.45,0, 0.12
> [ INFO] [1623836725.443801519, 0.608000000]: Calculated wheel_separation_h: 2.9
> [ INFO] [1623836725.443859610, 0.608000000]: Retrieved wheel_radius: 0.025
> [ INFO] [1623836725.444142081, 0.608000000]: Odometry params : wheel separation height 2.9, wheel radius 0.025
> [ INFO] [1623836725.448045047, 0.611000000]: Adding the rear wheel with joint name: rear_wheel_joint
> [ INFO] [1623836725.448208780, 0.612000000]: Adding the front steer with joint name: front_steer_joint
> [ INFO] [1623836725.448444482, 0.613000000]: Adding the subscriber: cmd_vel
> [ INFO] [1623836725.457789528, 0.622000000]: Finished controller initialization
> [INFO] [1623836725.458526, 0.622000]: Controller Spawner: Loaded controllers: joint_state_publisher, ackermann_steering_controller
> [INFO] [1623836725.468406, 0.632000]: Started controllers: joint_state_publisher, ackermann_steering_controller

**Comment by srmainwaring** [comment]
@tomlogan501 it's quite hard to determine what might be causing your rover to not display without some code to work by. 

Have you succeeded in getting the version in `master` to run and display correctly? If that's the case then the next stage would be to fork the repo, create a branch for your own robot and replace / modify the URDF. If you are able to post a link to that I can take a look at it and see what's going on with your example. You will need to make sure the names of the joints in your URDF and the controller configuration are all consistent.

**Comment by tomlogan501** [comment]
After a day on it, I get a good result but a weird behavior : in rviz the TF tree seems ok but on Gazebo the wheels are under the robot 

Is there extra configuration before spawn the model in gazebo or on the plugin ?

Thanks for your help anyway.

**Comment by srmainwaring** [comment]
That is a bit odd - that looks like it might be a relative vs absolute frame issue when defining the joints. IIRC Gazebo11 supports links relative to the joint origin, previous versions don't. Are you able to get all the collision primitives in the right place (i.e. re-dimension the steer bot URDF but don't drop in the mesh files until all that is working)? That might help narrow the problem down to correctly positioning and centring the visuals.

**Comment by tomlogan501** [comment]
I confirm the same behavior on gazebo 11.
I will try to narrow by starting with the steer bot URDF.

**Comment by srmainwaring** [comment]
@tomlogan501 I think we resolved this offline, so closing.

**Comment by tomlogan501** [comment]
@srmainwaring yeah sure, a good method is to start from your bot or fork the repo.
