### ISSUE TITLE
Feature request - ROS2

### ISSUE THREAD

**Issue by brianlmerritt** [srmainwaring/steer_bot#19]
I see this was packaged for ROS Indigo, but it doesn't appear to have a ROS2 version.

Any plans to update to ROS2?  There seems to be a lack of Ackermann steering controls there (please correct me if I am mistaken).

This is a feature request, not a bug.

**Comment by srmainwaring** [comment]
@brianlmerritt apologies for the long delay - yes I would like to get running on ROS2, however my dev environment is macOS so there have been some detours along the way to get dependencies up and running (Ignition support for macOS being the big one). I'll ping you when it's done - or PR's are welcome if you're interested in contributing.

**Comment by sezer-muhammed** [comment]
Yes ROS2 support would be awesome,
Thanks for repo
